<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crawl.io</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        td,th { text-align : center }
        img { border : 4px solid black;
              border-radius : 10px
        }
        .clickbox {
            border : 2px solid black;
            border-radius : 0px 30px 30px 15px;
            margin : 30px;
            padding : 10px;
            background-color : white;
            cursor : pointer;
            color : black;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="thumbnail">
                    <img src="<?= $TPL['base_path'] ?>img/areas/entrance.png" class="img-fluid" alt="Your doom awaits...">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-center clickbox" onclick="window.location.href='<?= $TPL['base_path'] ?>start'">
                Enter... If you dare!
            </div>
        </div>
        <div class="row">
            <div class="col text-center clickbox">
                Assignment by <? include "me.php" ?> and Dr Nicholas Moore <br>
                Music kindly provided by Simon Galton <br>
                Art Assets (mostly) generated by ChatGPT and ImageFX <br>
            </div>
        </div>
    </div>
</body>
</html>
